### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by baochengxu** [xlhomme/WCSTerrainProvider#1]
how to use it?

**Comment by xlhomme** [comment]
Something like :  
 var WCSTerrainProvider = new Cesium.WCSTerrainProvider({
                    service: "WCS",
                    url: "http://localhost:8080/geoserver/wcs",
                    layerName: "layerName",
                    bbox: [longitude - 0.1, latitude - 0.1, longitude + 0.1, latitude + 0.1],
                    waterMask: false
                });

   cesiumContainer.scene.terrainProvider = WCSTerrainProvider;

**Comment by baochengxu** [comment]
always show me  "404 Not Found"

**Comment by baochengxu** [comment]
Thank you very much~

**Comment by xlhomme** [comment]
Added this sample on the first page
