### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by BigDog6432** [xlhomme/WCSTerrainProvider#3]
Xavier,

The GeotiffParser is licensed under a Mozilla Public License 2.0.  What is WCSTerrainProvider licensed under? 

Thanks in advance

**Comment by xlhomme** [comment]
Hi
 Nothing is written on the file or with the file. Then you could use the code and do with you want with it. ... Mozilla or Lgpl licensing should be use.

**Comment by BigDog6432** [comment]
Xavier,

Thanks for the quick response.
